name: Build and Publish Package
env:
  VersionSuffix: ""
  DOTNET_NOLOGO: true
  VersionPrefix: 1.0.0
  Version: 1.0.0

on:
  push:
    branches:
      - $default-branch
    tags:
      - v[0-9]+.[0-9]+*
  pull_request:

jobs:
  Build_and_publish:
    runs-on: sravni_infra_build_small
    strategy:
      matrix:
        package_name:
          - "CHANGE_ME"
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
        env:
          DOTNET_INSTALL_DIR: ./dotnet

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ matrix.package_name }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-${{ matrix.package_name }}

      - name: Format version
        if: startsWith(github.ref, 'refs/tags')
        run: |
          tag=${GITHUB_REF#refs/tags/v}
          echo "Version=$tag" >> $GITHUB_ENV
          echo "VersionPrefix=$(echo $tag | cut -d- -f1)" >> $GITHUB_ENV
          echo "VersionSuffix=$(echo $GITHUB_REF | cut -d- -f2- -s)" >> $GITHUB_ENV
      
      - name: Setup nuget
        run: |
          dotnet nuget remove source nuget.org | true 
          dotnet nuget remove source artifactory | true 
          dotnet nuget add source \
            https://artifactory.yc.prod.infra.sravni.market/artifactory/api/nuget/v3/sravni_nuget_group/index.json \
            --name artifactory \
            --username ${{secrets.ARTIFACTORY_SVC_USERNAME}} \
            --password ${{secrets.ARTIFACTORY_SVC_PASSWORD}} \
            --protocol-version 3 \
            --store-password-in-clear-text

      - name: Build
        run: dotnet build -c Release /p:VersionPrefix=$VersionPrefix /p:VersionSuffix=$VersionSuffix /p:PackageVersion=$Version

      - name: Test
        run: dotnet test -c Release --no-build --filter "Category != LocalOnly"

      - name: Publish
        if: startsWith(github.ref, 'refs/tags')
        run: |
          dotnet nuget push ./${{ matrix.package_name }}/bin/Release/${{ matrix.package_name }}.*.nupkg \
            --source artifactory \
            --api-key '${{secrets.ARTIFACTORY_SVC_USERNAME}}:${{secrets.ARTIFACTORY_SVC_TOKEN}}'

