name: Delete-from-dev

# Удаляет проекты из dev при закрытии PR или удалении ветки

on:
  pull_request:
    types:
      - closed
  delete:
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Имя ветки'
        required: true
        type: string

env:
  ### Название команды
  # Необходимо указать название своей команды
  team: ""

  ### Название файла со значениями для helm-чарта
  # Необходимо изменить, если он называется по-другому 
  k8s_yaml_file_name: "ya-dev.yaml"

jobs:
  vars:
    name: Setup variables
    runs-on: ubuntu-latest
    outputs:
      team: ${{ steps.set_team.outputs.team }}
      branch: ${{ steps.branch_dispatch.outputs.branch || steps.branch_delete.outputs.branch || steps.branch_pr.outputs.branch }}
      k8s_yaml_file_name: ${{ steps.set_k8s_yaml.outputs.k8s_yaml_file_name }}
    steps:
      - name: Set team
        id: set_team
        run: echo "team=${team,,}" >> $GITHUB_OUTPUT
      - name: Set k8s file name
        id: set_k8s_yaml
        run: echo "k8s_yaml_file_name=${{ env.k8s_yaml_file_name }}" >> $GITHUB_OUTPUT
      - name: Set branch (dispatch)
        id: branch_dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: B="${{ github.event.inputs.branch_name }}" && echo "branch=${B,,}" >> $GITHUB_OUTPUT
      - name: Set branch (delete)
        id: branch_delete
        if: ${{ github.event_name == 'delete' }}
        run: B="${{ github.event.ref }}" && echo "branch=${B#refs/heads/}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_OUTPUT
      - name: Set branch (pull_request)
        id: branch_pr
        if: ${{ github.event_name == 'pull_request' }}
        run: B="${{ github.event.pull_request.head.ref }}" && echo "branch=${B,,}" >> $GITHUB_OUTPUT
  
  validate_branch:
    runs-on: ubuntu-latest
    needs: vars
    steps:
      - name: Break on master
        id: break_on_master
        if: ${{ needs.vars.outputs.branch == 'master' }}
        run:
          echo 'Нельзя удалять master' && exit 1

  get_projects:
    needs: [vars, validate_branch]
    uses: sravni/.github/.github/workflows/get-projects.yaml@master
    with:
      k8s_yaml_file_name: ${{ needs.vars.outputs.k8s_yaml_file_name }}

  delete:
    needs: [vars, get_projects]
    uses: sravni/.github/.github/workflows/delete-from-dev.yaml@master
    with:
      team: ${{ needs.vars.outputs.team }}
      branch: ${{ needs.vars.outputs.branch }}
      projects: ${{ needs.get_projects.outputs.projects }}
    secrets:
      TEST_CI_PAT_FOR_ACTIONS: ${{ secrets.TEST_CI_PAT_FOR_ACTIONS }}
      