name: Build-and-Test-BackOffices

on:
  push:
    branches-ignore:
      - master

env:
  team: ${{ secrets.TEAM }}
  image_pull_secret_acr: sravni-azurecr-io

jobs:
  get_backoffices:
    runs-on: ubuntu-latest
    outputs:
      backoffices: ${{ steps.get-backoffices.outputs.backoffices }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get backoffices
        id: get-backoffices
        run: |
          backoffices=(*.Backoffice)
          echo "backoffices list: ${backoffices}"
          echo "::set-output name=backoffices::${backoffices}"

  build_and_test:
    runs-on: ubuntu-latest
    needs: [get_backoffices]

    strategy:
      matrix:
        backoffice: ${{ needs.get_backoffices.outputs.backoffices }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set build vars to GITHUB_ENV
        run: |
          backoffice_name=${{ matrix.backoffice }}
          backoffice_name=$(echo "${backoffice_name}" | tr '[:upper:]' '[:lower:]')
          backoffice_name=${backoffice_name//./-}
          branch=$(echo ${GITHUB_REF#refs/heads/})
          sha=$(echo ${GITHUB_SHA} | cut -c1-7)
          build_number=$sha-qa
          image_name="${{ secrets.CONTAINER_REGISTRY }}/${backoffice_name}:${build_number}"
          echo "backoffice_name=$backoffice_name" >> $GITHUB_ENV
          echo "branch=$branch" >> $GITHUB_ENV
          echo "build_number=$build_number" >> $GITHUB_ENV
          echo "image_name=$image_name" >> $GITHUB_ENV

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Validate values files
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASS }}
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          image: ${{ secrets.CONTAINER_REGISTRY }}/qa-environment-helpers:${{ secrets.QA_ENVIRONMENT_HELPERS_TAG }}
          options: --rm -i -v ${{ github.workspace }}:/app
          run: |
            for file in /app/${{ matrix.backoffice }}/.k8s/*.yaml;
            do
              yamale -s /charts/generic-application/schema.yaml $file
            done

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Build
        run: |
          echo "Building image ${{ env.image_name }}"
          docker buildx build \
            --progress plain \
            --load \
            --force-rm \
            --build-arg GITHUB_USERNAME=${{ secrets.NUGET_USERNAME }} \
            --build-arg GITHUB_TOKEN=${{ secrets.GH_TOKEN }} \
            -t "${{ env.image_name }}" -f "./${{ matrix.backoffice }}/Dockerfile" .

      - name: Trivy Scanning
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.image_name }}'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
