name: Publish-to-Dev 

on:
  push:
    branches:
      - "master"
  workflow_dispatch:
    inputs:
      project_type:
        description: 'Проекты для публикации'
        required: false
        default: '*'
        type: choice
        options:
          - '*'
          - '*.Service'
          - '*.Backoffice'
          - '*.Job'

env:
  ### Название команды
  # Необходимо указать название своей команды
  team: ""
  
  ### Название файла со значениями для helm-чарта
  # Необходимо изменить, если он называется по-другому 
  k8s_yaml_file_name: "ya-dev.yaml"

jobs:
  vars: 
    name: Setup variables
    runs-on: ubuntu-latest
    outputs:
      team: ${{ steps.set_team.outputs.team }}
      values: ${{ steps.set_values.outputs.values }}
    steps:
      - name: Set team
        id: set_team
        run: echo "team=${team,,}" >> $GITHUB_OUTPUT
      - name: Set values file name
        id: set_values
        run: echo "values=${k8s_yaml_file_name,,}" >> $GITHUB_OUTPUT
   
  build_and_test:
    needs: [vars]
    uses: sravni/.github/.github/workflows/sravni-pipeline-build-and-test-multi-project-module.yml@get_projects
    with:
      is_stage: true
      with_push: true
      project_path_mask: ${{ github.event.inputs.project_type || '*' }}
      k8s_yaml_file_name: ${{ needs.vars.outputs.values }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  
  deploy:
    needs: [build_and_test, vars]
    uses: sravni/.github/.github/workflows/sravni-pipeline-publish-to-dev-multi-projects-module.yaml@get_projects
    with:
      projects: ${{ needs.build_and_test.outputs.projects }}
      team: ${{ needs.vars.outputs.team }}
    secrets:
      TEST_CI_PAT_FOR_ACTIONS: ${{ secrets.TEST_CI_PAT_FOR_ACTIONS }}
  