#Имя воркфлоу - будет отображаться во вкладке Actions в гитхабе
name: Build-and-Test-Multi-Jobs

#Запуск на любой пуш в любую ветку отличную от master/yandex
on:
  push:
    branches-ignore:
      - master
      - yandex

env:
  image_pull_secret_acr: sravni-azurecr-io

#Описание Джобов воркфлоу
jobs:
  #Описание Джобы get_jobs и ее шага, в котором происходит составление
  #матрицы сервисов по маске *.Job и ее сохранения для дальнейшего использования
  get_jobs:
    runs-on: ubuntu-latest

    outputs:
      jobs: ${{ steps.get-jobs.outputs.jobs }}

    steps:
      - uses: actions/checkout@v2
      - name: Get jobs
        id: get-jobs
        run: |
          jobs=$(ls -d *.Job | jq -R '[.]' | jq -s -c 'add')
          echo "Jobs list: ${jobs}"
          echo "::set-output name=jobs::${jobs}"

#Описание Джобы build_and_test и ее шагов:
  build_and_test:
    #runs-on указывает какой раннер будет использоваться для запуска данной Джобы
    #ubuntu-latest - офф раннер гитхаба на основе дистрибутива ubuntu
    #раннеры на основе других дистрибутивов можно найти в следующей доке:
    #https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    #                           !!!!!!!!!!!!ВАЖНО!!!!!!!!!!
    #sravni_ycloud_stage - наш раннер, необходимо указывать при наличии интегротестов
    #                          !!!!!!!!!!!!!!!!!!!!!!!!!!!!
    runs-on: ubuntu-latest
    needs: [get_jobs]

    #Все шаги будут примерняться на матрице, полученной в предыдущей джобе
    strategy:
      matrix:
        job: ${{ fromJson(needs.get_jobs.outputs.jobs) }}

    #checkout - собственно чекаут репозитория
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      #Шаг получения необходимых переменных для работы пайплайна
      #job_name - получается из имени репозитория, например osago-frontend
      #build_number - тег нашего образа, состоит из sha коммита и постфикса qa для стейдж окружения, для прода постфикс отсутствует
      #image_name - полное имя образа, к примеру sravni.azurecr.io/osago-frontend:ha751ufq
      - name: Set build vars to GITHUB_ENV
        run: |
          job_name=${{ matrix.job }}
          job_name=$(echo "${job_name}" | tr '[:upper:]' '[:lower:]')
          job_name=${job_name//./-}
          build_number=$(echo ${GITHUB_SHA} | cut -c1-7)
          image_name="${{ secrets.CONTAINER_REGISTRY }}/${job_name}:${build_number}"
          echo "build_number=$build_number" >> $GITHUB_ENV
          echo "image_name=$image_name" >> $GITHUB_ENV

      #Шаг логина в наш реджестри в Azure
      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASS }}

      #Шаг установки buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      #Шаг сборки образа (без пуша)
      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.job }}/Dockerfile
          build-args: |
            build_number=${{ env.build_number }}
            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
            GITHUB_USERNAME=sravni
            GITHUB_NPM_TOKEN=${{ secrets.GH_TOKEN }}
          push: false
          tags: "${{ env.image_name }}"

      # Сканирование образа на уязвимости
      - name: Trivy Scanning
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.image_name }}'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'