name: publish to stage services

#Запуск на любой пуш в ветку master/yandex или на PR в них
on:
  push:
    branches:
      - master
      
  workflow_dispatch:
    inputs:
      target_namespace:
        description: 'Namespace'
        required: false 
        type: string
  
#Описание Джобов воркфлоу
jobs:
  publish_to_stage:
    uses: sravni/.github/.github/workflows/sravni-pipeline-publish-to-stage-multi-services-base-module.yml@master
    with: 
      target_namespace: ${{ github.event.inputs.target_namespace }}
      team: <<Тут нужно написать имя своей команды. Такое же, как в кибане!!!>>
    secrets: 
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      YANDEX_KEY: ${{ secrets.YANDEX_KEY }}
      YANDEX_CLOUD_ID: ${{ secrets.YANDEX_CLOUD_ID }}
      YANDEX_FOLDER_ID: ${{ secrets.YANDEX_FOLDER_ID }}
      QA_API_URL: ${{ secrets.QA_API_URL }}
      QAENV_REF: ${{ secrets.QAENV_REF }}
