name: Build and test module

on:
  workflow_call:
    inputs:
      is_stage:
        description: "Запускается ли план для публикации на стейдж"
        required: true
        type: boolean
      project_path_mask:
        description: "Маска пути к файлам проекта"
        required: false
        type: string
      runner:
        description: "Указывает какой раннер будет использоваться для запуска флоу"
        default: "sravni_infra"
        required: false
        type: string
      runner_bento:
        description: "Указывает какой раннер будет использоваться для сборки бенто сервиса"
        default: "sravni_infra_build_bentoml"
        required: false
        type: string
      image_version:
        description: "Версия образа"
        required: false
        type: string
      k8s_yaml_file_name:
        description: "Имя файла {environment}.yaml в директории .k8s проекта для валидации его наличия и передачи следующим джобам"
        required: true
        type: string

    secrets:
      GH_TOKEN:
        required: true
      HARBOR_REGISTRY:
        required: true
      HARBOR_LOGIN:
        required: true
      HARBOR_PASSWORD:
        required: true

    outputs:
      projects:
        description: "Собранные проекты"
        value: ${{ jobs.get_projects.outputs.projects }}

# Описание Джобов воркфлоу
jobs:
  # Описание Джобы get_projects и ее шага, в котором происходит составление
  # списка проектов для сборки.
  # | project_name | dockerfile | project_path | k8s_yaml_path | build_number | image_name | image_version |
  get_projects:
    uses: ./.github/workflows/get-projects.yaml
    with:
      k8s_yaml_file_name: ${{ inputs.k8s_yaml_file_name }}
      project_path_mask: ${{ inputs.project_path_mask }}
      image_version: ${{ inputs.image_version }}
      is_stage: ${{ inputs.is_stage }}
      runner: ${{ inputs.runner }}

  docker:
    name: Bento build
    runs-on: ${{ inputs.runner_bento }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_LOGIN }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - uses: bentoml/setup-bentoml-action@v1
        with:
          python-version: '3.10'
          bentoml-version: 'main'
      - run: pip install -r import_model_requirements.txt -i https://nexus.yc.prod.infra.sravni.market/repository/pypi.org_proxy/simple
      - run: python import_model.py
      - uses: bentoml/build-bento-action@v1
        id: bento
      - run: |
          echo "Bento tag: ${{ steps.bento.outputs.bento-tag }}"
          echo "Bento name: ${{ steps.bento.outputs.bento-name }}"
          echo "Bento version: ${{ steps.bento.outputs.bento-version }}"
          echo "Bento metadata: ${{ steps.bento.outputs.bento-metadata }}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
          version: v0.10.0
      - name: Bento build
        run: |
          bentoml containerize ${{ steps.bento.outputs.bento-tag }} \
          --push \
          --backend=buildx \
          --image-tag "${{ secrets.HARBOR_REGISTRY }}/${{ steps.bento.outputs.bento-name }}:${{ steps.bento.outputs.bento-version }}" \
          --opt build-arg:ENVIROMENT='stage' \
          --opt build-arg:GITHUB_TOKEN=${{ secrets.GH_TOKEN }} \
          --opt build-arg:GITHUB_USERNAME=sravni
