### Универсальный модуль сборки и публикации js проектов в npm registry
# Принимает на вход название команды и JSON с информацией о проектах для деплоя.
name: Build and Publish to npm registry

on:
  workflow_call:
    inputs:
      runner:
        description: "Указывает какой раннер будет использоваться для запуска флоу"
        required: false
        default: "sravni_infra_build_small"
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true
      ARTIFACTORY_SVC_TOKEN:
        required: true

jobs:
  build_and_publish:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          # Для обновления до 22 ноды и выше нужно в репозиториях перейти с node-sass на sass пакет
          node-version: '20.x'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install registry
        run: |
          npm config set registry https://artifactory.yc.prod.infra.sravni.market/artifactory/api/npm/sravni_npm_group/:_authToken=${{ secrets.ARTIFACTORY_SVC_TOKEN }}
          yarn config set registry https://artifactory.yc.prod.infra.sravni.market/artifactory/api/npm/sravni_npm_group/:_authToken=${{ secrets.ARTIFACTORY_SVC_TOKEN }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Publish dev version of package
        if: contains(github.ref, '-dev')
        run: yarn publish --tag dev

      - name: Publish stable version of package
        if: contains(github.ref, '-dev') != true
        run: yarn publish

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: contains(github.ref, '-dev') != true
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
