name: build and test with postgresql DB

on:
  workflow_call:
    inputs:
      is_stage:
        description: "Запускается ли план для публикации на стейдж"
        required: true
        type: boolean
      project_path_mask:
        description: "Маска пути к файлам проекта"
        required: true
        type: string
      with_push:
        description: "Пушить ли собранный образ"
        required: true
        type: boolean
      runner:
        description: "Указывает какой раннер будет использоваться для запуска флоу"
        default: "sravni_infra"
        required: false
        type: string
      image_version:
        description: "Версия образа"
        required: false
        type: string
      k8s_yaml_file_name:
        description: "Имя файла {environment}.yaml в директории .k8s проекта для валидации его наличия и передачи следующим джобам"
        required: true
        type: string
      db_image:
        description: "image БД"
        required: true
        type: string
      db_user_name:
        description: "Имя пользователя для БД"
        required: true
        type: string
      db_user_psw:
        description: "Пароль пользователя для БД"
        required: true
        type: string
      db_name:
        description: "Название базы данных"
        required: true
        type: string
      canary:
        description: "Включить канарейку"
        required: false
        type: boolean
        default: false

    secrets:
      GH_TOKEN:
        required: true
      GITHUB_NPM_TOKEN:
        required: true
      CONTAINER_REGISTRY:
        description: "harbor_registry"
        required: true
      DOCKER_LOGIN:
        description: "harbor_login"
        required: true
      DOCKER_PASS:
        description: "harbor_pass"
        required: true

    outputs:
      projects:
        description: "Собранные проекты"
        value: ${{ jobs.get_projects.outputs.projects }}

# Описание Джобов воркфлоу
jobs:
  # Описание Джобы get_projects и ее шага, в котором происходит составление
  # списка проектов для сборки.
  # | project_name | dockerfile | project_path | k8s_yaml_path | build_number | image_name | image_version |
  get_projects:
    uses: sravni/.github/.github/workflows/get-projects.yaml@master
    with:
      k8s_yaml_file_name: ${{ inputs.k8s_yaml_file_name }}
      project_path_mask: ${{ inputs.project_path_mask }}
      image_version: ${{ inputs.image_version }}
      is_stage: ${{ inputs.is_stage }}
      runner: ${{ inputs.runner }}

  build_and_test:
    needs: [get_projects]
    runs-on: ${{ inputs.runner }}

    # Service containers to run with `db_setup`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: ${{ inputs.db_image }}
        # Provide the config for postgres with host 127.0.0.1
        env:
          POSTGRES_USER: ${{ inputs.db_user_name }}
          POSTGRES_PASSWORD: ${{ inputs.db_user_psw }}
          POSTGRES_DB: ${{ inputs.db_name }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 6432:5432

    strategy:
      matrix:
        project: ${{ fromJson(needs.get_projects.outputs.projects) }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: build and test
        uses: sravni/build-and-test-action@v1
        with:
          is_stage: true
          with_push: true
          gh_token: ${{ secrets.GH_TOKEN }}
          github_npm_token: ${{ secrets.GITHUB_NPM_TOKEN }}
          container_registry: ${{ secrets.CONTAINER_REGISTRY }}
          docker_login: ${{ secrets.DOCKER_LOGIN }}
          docker_pass: ${{ secrets.DOCKER_PASS }}
