name: Build and test module

on:
  workflow_call:
    inputs:
      is_stage:
        description: "Запускается ли план для публикации на стейдж"
        required: true
        type: boolean
      project_path_mask:
        description: "Маска пути к файлам проекта"
        required: true
        type: string
      with_push:
        description: "Пушить ли собранный образ"
        required: true
        type: boolean
      runner:
        description: "Указывает какой раннер будет использоваться для запуска флоу"
        default: "sravni_infra"
        required: false
        type: string
      image_version:
        description: "Версия образа"
        required: false
        type: string
      k8s_yaml_file_name:
        description: "Имя файла {environment}.yaml в директории .k8s проекта для валидации его наличия и передачи следующим джобам"
        required: true
        type: string
      canary:
        description: "Включить канарейку"
        required: false
        type: boolean
        default: false

    secrets:
      GH_TOKEN:
        required: true
      GITHUB_NPM_TOKEN:
        required: true
      HARBOR_REGISTRY:
        required: true
      HARBOR_LOGIN:
        required: true
      HARBOR_PASS:
        required: true
      NEXTAUTH_URL:         # Добавлено для команды MFO
        required: false     #
      NEXTAUTH_SECRET:      # Добавлено для команды MFO
        required: false     #
      SLACK_CLIENT_SECRET:  # Добавлено для команды MFO
        required: false     #
      SLACK_CLIENT_ID:      # Добавлено для команды MFO
        required: false     #     #
      JUICY_SCORE_API_KEY_DEV:  # Добавлено для команды MFO
        required: false     #
      JUICY_SCORE_API_KEY_PROD: # Добавлено для команды MFO
        required: false     #
      ALLURE_TOKEN:         # Добавлено для команды Mobile
        required: false     #
      SENTRY_SOURCEMAP_WEB_FRONTEND_AUTH_TOKEN: # AUTH токен для source map сентри, добавлено для команды OSAGO
        required: false

    outputs:
      projects:
        description: "Собранные проекты"
        value: ${{ jobs.get_projects.outputs.projects }}

env:
  CANARY: ${{ inputs.canary }}

# Описание Джобов воркфлоу
jobs:
  # Описание Джобы get_projects и ее шага, в котором происходит составление
  # списка проектов для сборки.
  # | project_name | dockerfile | project_path | k8s_yaml_path | build_number | image_name | image_version |
  get_projects:
    uses: ./.github/workflows/get-projects.yaml
    with:
      k8s_yaml_file_name: ${{ inputs.k8s_yaml_file_name }}
      project_path_mask: ${{ inputs.project_path_mask }}
      image_version: ${{ inputs.image_version }}
      is_stage: ${{ inputs.is_stage }}
      runner: ${{ inputs.runner }}

  build_and_test:
    runs-on: ${{ inputs.runner }}
    needs: [get_projects]

    strategy:
      matrix:
        project: ${{ fromJson(needs.get_projects.outputs.projects) }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_LOGIN }}
          password: ${{ secrets.HARBOR_PASS }}

      - name: Check if image is a canary
        run: |
          if [[ "${{ env.CANARY }}" == 'true' ]]
          then
          canary_tag="canary-"
          else
            canary_tag=""
          fi
          echo "CANARY_TAG=$canary_tag" >> $GITHUB_ENV

      - name: Check if image exist
        run: |
          inspect_result=$(docker manifest inspect "${{ secrets.HARBOR_REGISTRY }}/${{ env.CANARY_TAG }}${{ matrix.project.image_name }}" > /dev/null 2>&1; echo $?)
          if [ $inspect_result -eq 1 ]
          then
            echo "IMAGE_EXIST=false" >> $GITHUB_ENV
          else
            echo "IMAGE_EXIST=true" >> $GITHUB_ENV
            echo "Образ ${{ matrix.project.image_name }} уже cуществует"
          fi

      - name: Set up Docker Buildx
        if: ${{ env.IMAGE_EXIST == 'false' }}
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.16.2
          driver-opts: image=registry.yc.prod.infra.sravni.market/docker_proxies/moby/buildkit:buildx-stable-1

      - name: Docker build
        if: ${{ env.IMAGE_EXIST == 'false' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.project.dockerfile }}
          build-args: |
            build_number=${{ matrix.project.build_number }}
            ENVIROMENT=${{ inputs.is_stage && 'stage' || 'production'  }}
            # Frontend разработчики в своих проектах используют такое название
            ENV=${{ inputs.is_stage && 'stage' || 'production'  }}
            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
            GITHUB_USERNAME=sravni
            GITHUB_NPM_TOKEN=${{ secrets.GH_TOKEN }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            SLACK_CLIENT_SECRET=${{ secrets.SLACK_CLIENT_SECRET }}
            SLACK_CLIENT_ID=${{ secrets.SLACK_CLIENT_ID }}
            JUICY_SCORE_API_KEY_DEV=${{ secrets.JUICY_SCORE_API_KEY_DEV }}
            JUICY_SCORE_API_KEY_PROD=${{ secrets.JUICY_SCORE_API_KEY_PROD }}
            ALLURE_TOKEN=${{ secrets.ALLURE_TOKEN }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_SOURCEMAP_WEB_FRONTEND_AUTH_TOKEN }}
          push: ${{ inputs.with_push }}
          tags: "${{ secrets.HARBOR_REGISTRY }}/${{ env.CANARY_TAG }}${{ matrix.project.image_name }}"
