### Универсальный модуль публикации проектов на STAGE
# Принимает на вход название команды и JSON с информацией о проектах для деплоя.

name: Publish to stage projects base module

on:
  workflow_call:
    inputs:
      team:
        description: 'team'
        required: true
        type: string
      projects:
        description: "JSON объект со списком проектов для публикации"
        required: true
        type: string
      url_prefix:
        description: "Префикс адреса ингресса (если пусто, то используется имя ветки)"
        required: false
        type: string
        default: ''
      runner:
        description: "Указывает какой раннер будет использоваться для запуска флоу"
        required: false
        default: sravni_infra_build_small
        type: string
    secrets:
      TEST_CI_PAT_FOR_ACTIONS:
        required: true
      HARBOR_REGISTRY:
        required: true
      HARBOR_LOGIN:
        required: true
      HARBOR_PASSWORD:
        required: true

env:
  TEAM: ${{ inputs.team }}

jobs:
  vars:
    name: Setup variables
    runs-on: ${{ inputs.runner }}
    outputs:
      team: ${{ steps.set_team.outputs.team }}
    steps:
      - name: Set team
        id: set_team
        run: echo "team=${TEAM,,}" >> $GITHUB_OUTPUT

  publish:
    runs-on: ${{ inputs.runner }}
    needs: [ vars ]

    env:
      TEAM: ${{ needs.vars.outputs.team }}
      REPO_PATH: './deploy/${{ needs.vars.outputs.team }}'
      YQ_VERSION: '4.30.3'
      SCAN_TOKEN: ${{ secrets.VSK_TOKEN }}
      API_URL_DEPLOY_IN: https://89.169.173.82:19445/api/vizhn
      API_URL_DEPLOY_OUT: https://vizhn.sravni.local/api/vizhn
      REPO_NAME: ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}

    strategy:
      max-parallel: 1
      matrix:
        project: ${{ fromJson(inputs.projects) }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Checkout deploy repo
        uses: actions/checkout@v4
        with:
          repository: sravni/deploy_${{ env.TEAM }}
          token: ${{ secrets.TEST_CI_PAT_FOR_ACTIONS }}
          path: deploy
          ref: main

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_LOGIN }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      # Проверка - существует ли приложение в dev окружении.
      - name: Ensure project exist
        run: |
          if [[ -d ${{ env.REPO_PATH }}/${{ matrix.project.project_name }} ]];
          then
            echo 'Проект ${{ env.REPO_PATH }}/${{ matrix.project.project_name }} уже существует'
          else
            echo 'Проект ${{ env.REPO_PATH }}/${{ matrix.project.project_name }} не существует, создайте его сначала в dev окружении!'
          fi;

      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v${{ env.YQ_VERSION }}/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      # Копирование *.yaml файла с вэйльюсами из репы сервиса в deploy. Фактическое название файла приходит в JSON'е в projects.
      # Имя этого файла должно стать values_mpl_stage.yaml.
      - name: Clone values from origin repo
        run: |
          cat ${{ matrix.project.k8s_yaml_path }} > ${{ env.REPO_PATH }}/${{ matrix.project.project_name }}/values_mpl_stage.yaml;

      - name: Create app
        run: >
          grep -xq '  - name: ${{ matrix.project.project_name }}' ${{ env.REPO_PATH }}/_apps/values_mpl_stage.yaml
          || yq e  -i '.services += {"name": "${{ matrix.project.project_name }}"}' ${{ env.REPO_PATH }}/_apps/values_mpl_stage.yaml;

      # Устанавливаем tag образа и убеждаемся, что установлены `global.image.repository` и `global.imagePullSecrets`
      - name: Modify values
        run: >
          yq -i '.global.image.tag = "${{ matrix.project.image_version }}" |
          .global.image.repository = "registry.yc.prod.infra.sravni.market/${{ env.TEAM }}_mpl_stage/${{ matrix.project.project_name }}" |
          .global.imagePullSecrets[0] = "harbor-pull-secret"'
          ${{ env.REPO_PATH }}/${{ matrix.project.project_name }}/values_mpl_stage.yaml;

      # Если используется репа deploy для команды (например deploy_devops) 
      # то прописываются переменные которые меняют repoURL в argocd application для сервиса
      - name: Tag application with repoURL
        run: |
          KEY=$(yq '.services | to_entries | .[] | select(.value.name == "${{ matrix.project.project_name }}") | .key' ${{ env.REPO_PATH }}/_apps/values_mpl_stage.yaml);
          REPOURL=$(yq e ".services[$KEY].repoURL" ${{ env.REPO_PATH }}/_apps/values_mpl_stage.yaml);
          if [[ $REPOURL == "https://sravni.gitlab.yandexcloud.net/${{ env.TEAM }}_group/deploy_${{ env.TEAM }}.git" ]]; then 
            echo "Данный сервис теперь живет в гитлабе, запускайте пайплайны там https://sravni.gitlab.yandexcloud.net/${{ env.TEAM }}_group"
            exit 1
          else
            yq -i e ".services[$KEY].repoURL = \"https://github.com/sravni/deploy_${{ env.TEAM }}\", .services[$KEY].branch = \"main\"" ${{ env.REPO_PATH }}/_apps/values_mpl_stage.yaml
          fi

      # Обновляем зависимости чартов
      - name: Helm dep update
        working-directory: ${{ env.REPO_PATH }}/${{ matrix.project.project_name }}
        run: helm dependency update
      
      # Проверяем сборку темплейтов
      - name: Helm check
        working-directory: ${{ env.REPO_PATH }}/${{ matrix.project.project_name }}
        run: helm template . -f values_mpl_stage.yaml
      
      - name: Helm check cleanup
        working-directory: ${{ env.REPO_PATH }}/${{ matrix.project.project_name }}
        run:  |
          rm -rf charts/ && rm Chart.lock
          
      # Добавляет коммит для поля info в Argo вида
      # commit: sravni/mortgageinsurance/commit/2b13e85a9c5e439b79e406f08a0cde673fa1f4a3
      - name: Adding commit SHA
        run: >
          FULL_SHA=${GITHUB_SHA}
          && GIT_REPO=${GITHUB_REPOSITORY}
          && KEY=$(yq '.services | to_entries | .[] | select(.value.name == "${{ matrix.project.project_name }}") | .key' ${{ env.REPO_PATH }}/_apps/values_mpl_stage.yaml)
          && yq -i e ".services[$KEY].commit = \"$GIT_REPO/commit/$FULL_SHA\"" ${{ env.REPO_PATH }}/_apps/values_mpl_stage.yaml

      - name: Do rebase and commit
        run: >
          cd ./deploy
          && git add .
          && git -c user.name="sravnidevops" -c user.email="company-service@sravni.ru" commit --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>" -m "${{ matrix.project.project_name }} new version: ${{ matrix.project.image_version }}"
          && git -c user.name="sravnidevops" -c user.email="company-service@sravni.ru" pull --rebase
          && git push origin main || sleep 10
          && git -c user.name="sravnidevops" -c user.email="company-service@sravni.ru" pull --rebase
          && git push origin main
          && cd ../

      - name: Run SAST scan tests
        run: >
          curl --max-time 60 -X POST -k "${{ env.API_URL_DEPLOY_IN }}?&repo=${{ env.REPO_NAME }}&token=$SCAN_TOKEN" || curl --max-time 60 -X POST -k "${{ env.API_URL_DEPLOY_OUT }}?&repo=${{ env.REPO_NAME }}&token=$SCAN_TOKEN"
        continue-on-error: true
