name: Get service name by git

on:
  workflow_call:
    inputs:
      runner:
        description: "Указывает какой раннер будет использоваться для запуска флоу"
        default: "sravni_ycloud_stage"
        required: false
        type: string
    outputs:
      service_name:
        description: "Название сервиса полученное после выполнения workflow"
        value: ${{ jobs.get_service_name.outputs.service_name }}

jobs:
  get_service_name:
    runs-on: ${{ inputs.runner }}

    outputs:
      service_name: ${{ steps.out_service_name.outputs.service_name }}

    steps:
      - name: Get service name
        run: | 
          service_name=$(basename `git rev-parse --show-toplevel`)
          echo "SERVICE_NAME=$service_name" >> $GITHUB_ENV        

      - id: out_service_name
        run: |
          echo "::set-output name=service_name::${{ env.SERVICE_NAME }}"

   