name: Publish to dev mono projects base module

on:
  workflow_call:
    inputs:
      team:
        description: 'team'
        required: true 
        type: string
      image-id:
        description: "Тэг докер имажа который хотим выкатить"
        required: true
        type: string
      runner:
        description: "Указывает какой раннер будет использоваться для запуска флоу"
        required: false
        default: sravni_dev
        type: string
    secrets: 
      TEST_CI_PAT_FOR_ACTIONS:
        required: true

env:
  TEAM: ${{ inputs.team }}
  IMAGE_ID: ${{ inputs.image-id }}

jobs:
  publish:
    runs-on: ${{ inputs.runner }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set env
        run: |
          echo "SERVICE=${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "GITHUB_BRANCH=$(echo $GITHUB_REF | cut -d'/' -f4)" >> $GITHUB_ENV
          echo "REPO_PATH=./deploy" >> $GITHUB_ENV
          echo "YQ_VERSION=4.30.3" >> $GITHUB_ENV

      - name: Checkout deploy repo
        uses: actions/checkout@v3
        with:
          repository: sravni/deploy
          token: ${{ secrets.TEST_CI_PAT_FOR_ACTIONS }}
          path: deploy
          ref: main

      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v${{ env.YQ_VERSION }}/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Create app
        run: |
          if [ ! -f "./deploy/${{ env.TEAM }}/${{ env.SERVICE }}/values_${{ env.GITHUB_BRANCH }}.yaml" ]; then grep -q ${{ env.GITHUB_BRANCH }} ${{ env.REPO_PATH }}/${{ env.TEAM }}/_apps/values_dev.yaml || yq e  -i '.services += {"name": "${{ env.SERVICE }}-${{ env.GITHUB_BRANCH }}", "values_file": "values_${{ env.GITHUB_BRANCH }}.yaml", "nameOrigin": "${{ env.SERVICE }}"}' ${{ env.REPO_PATH }}/${{ env.TEAM }}/_apps/values_dev.yaml ; fi
      
      - name: Create values 
        run: |
          if [ ! -f "./deploy/${{ env.TEAM }}/${{ env.SERVICE }}/values_${{ env.GITHUB_BRANCH }}.yaml" ]; then yq e '.global.image.tag = "${{ env.build_number }}" | .ingresses[0].host |= sub ("(^)", "${{ env.GITHUB_BRANCH }}.${1}")  ' ${{ env.REPO_PATH }}/${{ env.TEAM }}/${{ env.SERVICE }}/values_dev.yaml > ${{ env.REPO_PATH }}/${{ env.TEAM }}/${{ env.SERVICE }}/values_${{ env.GITHUB_BRANCH }}.yaml ; fi

      - name: Modify values
        run: |
          yq -i '.global.image.tag = "${{ env.build_number }}"' ${{ env.REPO_PATH }}/${{ env.TEAM }}/${{ env.SERVICE }}/values_${{ env.GITHUB_BRANCH }}.yaml

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: ./deploy
          branch: main
          commit_user_name: sravnidevops
          commit_user_email: company-service@sravni.ru
          commit_message: '${{ env.SERVICE }}-branch-${{ env.GITHUB_BRANCH }} new version: ${{ env.build_number }}'
