name: Publish to dev  projects base module

on:
  workflow_call:
    inputs:
      team:
        description: 'team'
        required: true 
        type: string
      projects:
        description: "JSON объект со списком проектов для публикации"
        required: true
        type: string
      runner:
        description: "Указывает какой раннер будет использоваться для запуска флоу"
        required: false
        default: sravni_dev
        type: string
    secrets: 
      TEST_CI_PAT_FOR_ACTIONS:
        required: true

env:
  TEAM: ${{ inputs.team }}

jobs:
  publish:
    runs-on: ${{ inputs.runner }}

    strategy:
      matrix:
        project: ${{ fromJson(inputs.projects) }}

    steps:
      - name: Set env
        run: |
          echo "SERVICE_NAME=$(basename `git rev-parse --show-toplevel`)" >> $GITHUB_ENV
          echo "REPO_PATH=./deploy" >> $GITHUB_ENV
          echo "YQ_VERSION=4.30.3" >> $GITHUB_ENV
          echo "service_name is " $SERVICE_NAME

      - name: Checkout deploy repo
        uses: actions/checkout@v3
        with:
          repository: sravni/deploy
          token: ${{ secrets.TEST_CI_PAT_FOR_ACTIONS }}
          path: deploy
          ref: main

      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v${{ env.YQ_VERSION }}/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Modify values
        run: |
          yq -i '.global.image.tag = "${{ matrix.project.image_version }}"' ${{ env.REPO_PATH }}/${{ env.TEAM }}/${{ env.SERVICE_NAME }}/values_dev.yaml
      
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: deploy
          branch: main
          commit_user_name: sravnidevops
          commit_user_email: company-service@sravni.ru
          commit_message: "${{ env.SERVICE_NAME }} new version: ${{ matrix.project.image_version }}"
